# reference: https://github.com/akka/akka/blob/master/.travis.yml
language: scala
sudo: false

services:
  - docker

scala:
  - "2.11.12"
  - "2.12.11"
  - "2.13.3"

before-install:
  - curl -sL https://raw.githubusercontent.com/shyiko/jabba/0.11.2/install.sh | bash && . ~/.jabba/jabba.sh
  - jabba install "adopt@~1.$TRAVIS_JDK.0-0"

before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt  -name "*.lock"               -print -delete

cache:
  directories:
    - $HOME/.cache/coursier
    - $HOME/.ivy2/cache
    - $HOME/.sbt
    - $HOME/.jabba/sdk
  timeout: 900

script:
  # make 'git branch' work again
  - git branch -f "$TRAVIS_BRANCH" && git checkout "$TRAVIS_BRANCH"
  - docker-compose up -d
  - sbt ++$TRAVIS_SCALA_VERSION -jvm-opts .jvmopts-travis -Dakka.test.timefactor=2.0 "; update ; test"
  # check policies, if on master also upload
  - if [[ "$TRAVIS_SECURE_ENV_VARS" == "true" ]]; then if [[ "$TRAVIS_BRANCH" == "master" && "$TRAVIS_EVENT_TYPE" == "push" ]]; then sbt 'set credentials += Credentials("whitesource", "whitesourcesoftware.com", "", System.getenv("WHITESOURCE_KEY"))' whitesourceCheckPolicies whitesourceUpdate; else sbt 'set credentials += Credentials("whitesource", "whitesourcesoftware.com", "", System.getenv("WHITESOURCE_KEY"))' whitesourceCheckPolicies; fi; fi

after_failure:
  - docker-compose logs

env:
  global:
    - TRAVIS_JDK=8
    # encrypt with: travis encrypt WHITESOURCE_KEY=... --com
    - secure: "Pu2VJBCSm168zaYxxztX1kF/O4KlY6ZceXUlg/E8i3+Oy+y1gMXrMuFRRj4TLuEsQyaTI4lb7ifvJzAtXJgiChPttX+RN7EkD+5d7ItZh0xu5i4z8F746XYoH05XbTT4DKLJjwoKFCFjuQKGhilejcf3076gewummWnjK+A1PIK0T1hQqa3DBMiBuYuzWJbBzgVCaxwOOR4FsFR02uKgR5oWdWyqXE9tVillcHU5sUCkbyCnq9qNfytGfFBQFARd6SKJh564coK4njp84/nv25Cz9bgiS0T3big+lVbdGYhk0J53b7pdWiIGUQWs2gpqltRP+lKUkuqUfq5jnyEJTlVoJ2Zq8Rc/hjwTZnzkf1F5FdJ/XS2nQRFVub85a6zO7OZ22dhJLItYR0M/L8USpRHrX5bBx00T5QW1xUfBcdP6IUE83LSKQu3a9p1NdHdgacDEdE1PHNTe4dANw44q7szOCHKxtL59qcbGM3fiLQE9xa++60+IpdZOty1mYIWq533srYILqleUtcPF9Uvb6vdncsdK/mErtSZVNeMpzxP05rLFj2JJovcAkBMsjzLXqZyDiHk892/eriw628J8c5S1i/hswpS5dBzbHUgDNBpbyKMwBngA/+JKdGU+f3xHYu1dwbgdzQSOynaok/XdaTAJtqEGTRSsytofJ60d5LM="
